### ISSUE TITLE
sequencify plugins has problem

### ISSUE THREAD

**Issue by OnedayLiu** [eggjs/egg-view-ejs#4]
我在plugin.js开启该插件

`module.exports = {
  view: {
    enable: true,
    package: 'egg-view-ejs'
  }
}`

但是报错了
`PluginSequencifyError: sequencify plugins has problem, missing: [], recursive: [view,view]`

**Comment by popomore** [comment]
插件是 ejs，不是 view
OnedayLiu <notifications@github.com>于2017年3月7日 周二21:10写道：

**Comment by dead-horse** [comment]
```js
exports.ejs = {
  enable: true,
  package: 'egg-view-ejs',
};
```

配置方式看文档 https://eggjs.org/zh-cn/core/view.html
